import { Course, Test, LiveSession, VideoLecture, Notice, Testimonial, Category, User } from '../types';

export const currentUser: User = {
  id: 'usr_001',
  name: 'Rahul Sharma',
  email: 'rahul.sharma@raven.edu',
  role: 'student',
  registrationId: 'RAV-2025-8842',
  standard: 'Class 12 - PCM',
  phone: '+91 98765 43210',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
  enrolledCourses: ['c_001', 'c_002', 'c_003'],
  createdAt: '2024-06-15',
};

export const categories: Category[] = [
  { name: 'Science', count: 45, icon: 'flask', color: '#10B981' },
  { name: 'Mathematics', count: 32, icon: 'calculator', color: '#3B82F6' },
  { name: 'Technology', count: 28, icon: 'laptop', color: '#8B5CF6' },
  { name: 'Language', count: 15, icon: 'book', color: '#F59E0B' },
  { name: 'Commerce', count: 20, icon: 'trending-up', color: '#06B6D4' },
  { name: 'Arts', count: 12, icon: 'palette', color: '#EC4899' },
];

export const dummyCourses: Course[] = [
  {
    id: 'c_001',
    title: 'Complete Physics Masterclass',
    description: 'Master physics from fundamentals to IIT-JEE & NEET competitive level. Covers mechanics, thermodynamics, electromagnetism, optics, and modern physics with deep conceptual problem-solving.',
    shortDescription: 'Master physics from fundamentals to competitive level with conceptual clarity.',
    thumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=800&h=500&fit=crop',
    instructor: {
      id: 'inst_001',
      name: 'Dr. Priya Singh',
      qualification: 'Ph.D. IIT Delhi, 12+ Yrs Exp',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop',
    },
    category: 'Science',
    level: 'Intermediate',
    duration: '40 hours',
    totalLessons: 48,
    totalStudents: 1234,
    rating: 4.8,
    totalRatings: 312,
    price: 2999,
    originalPrice: 5999,
    isFree: false,
    isPopular: true,
    features: [
      '48 HD Video Lectures',
      'Daily Practice Problem Sets (DPPs)',
      '12 Chapter-wise Tests & Full Mock Tests',
      'Direct WhatsApp Doubt Resolution'
    ],
    syllabus: [
      'Kinematics and Dynamics in 1D & 2D',
      'Newton\'s Laws of Motion & Friction',
      'Work, Power, Energy & Circular Motion',
      'Rotational Dynamics & Moment of Inertia',
      'Gravitation & Simple Harmonic Motion'
    ],
    lessons: [
      { id: 'l_101', title: '01. Introduction to Physical World & Vectors', duration: '22:15', isCompleted: true, isFree: true, order: 1 },
      { id: 'l_102', title: '02. Dimensional Analysis & Error Propagation', duration: '28:40', isCompleted: true, isFree: true, order: 2 },
      { id: 'l_103', title: '03. Motion in a Straight Line - Calculus Approach', duration: '35:10', isCompleted: true, isFree: false, order: 3 },
      { id: 'l_104', title: '04. Projectile Motion & Relative Velocity', duration: '41:20', isCompleted: false, isFree: false, order: 4 },
      { id: 'l_105', title: '05. Newton\'s Second Law & Free Body Diagrams', duration: '45:00', isCompleted: false, isFree: false, order: 5 },
      { id: 'l_106', title: '06. Friction: Static vs Kinetic & Block on Block', duration: '38:50', isCompleted: false, isFree: false, order: 6 },
    ],
  },
  {
    id: 'c_002',
    title: 'Advanced Mathematics for JEE',
    description: 'Complete mathematics syllabus for JEE Main & Advanced covering algebra, coordinate geometry, differential and integral calculus, and vectors with over 2000 solved benchmark questions.',
    shortDescription: 'From core algebra to advanced calculus — complete JEE exam mastery.',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=500&fit=crop',
    instructor: {
      id: 'inst_002',
      name: 'Prof. Amit Kumar',
      qualification: 'M.Sc. Mathematics, IIT Kanpur',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop',
    },
    category: 'Mathematics',
    level: 'Advanced',
    duration: '60 hours',
    totalLessons: 72,
    totalStudents: 2567,
    rating: 4.9,
    totalRatings: 540,
    price: 3499,
    originalPrice: 6999,
    isFree: false,
    isPopular: true,
    features: [
      '72 In-depth Video Sessions',
      'Advanced Shortcut Tricks & Proofs',
      '25 Full JEE Main + Advanced Pattern Tests',
      'Formula Sheets & Quick Revision Mindmaps'
    ],
    syllabus: [
      'Complex Numbers & Quadratic Equations',
      'Permutations, Combinations & Binomial Theorem',
      'Limits, Continuity & Differentiability',
      'Applications of Derivatives (AOD)',
      'Indefinite & Definite Integrals'
    ],
    lessons: [
      { id: 'l_201', title: '01. Sets, Relations & Function Transformations', duration: '20:10', isCompleted: true, isFree: true, order: 1 },
      { id: 'l_202', title: '02. Complex Numbers - Geometry & Roots of Unity', duration: '32:45', isCompleted: true, isFree: true, order: 2 },
      { id: 'l_203', title: '03. Quadratic Equations - Location of Roots', duration: '27:15', isCompleted: false, isFree: false, order: 3 },
      { id: 'l_204', title: '04. Limits & L\'Hopital Rule Mastery', duration: '36:30', isCompleted: false, isFree: false, order: 4 },
      { id: 'l_205', title: '05. Maxima & Minima Optimization Techniques', duration: '44:10', isCompleted: false, isFree: false, order: 5 },
    ],
  },
  {
    id: 'c_003',
    title: 'Chemistry Fundamentals & Reactions',
    description: 'Master organic mechanisms, physical chemistry equations, and inorganic periodic trends. Tailored for CBSE boards and competitive medical/engineering entrances.',
    shortDescription: 'Interactive chemistry with reaction mechanisms and visual models.',
    thumbnail: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=800&h=500&fit=crop',
    instructor: {
      id: 'inst_003',
      name: 'Dr. Neha Gupta',
      qualification: 'Ph.D. Organic Chemistry',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    },
    category: 'Science',
    level: 'Beginner',
    duration: '35 hours',
    totalLessons: 42,
    totalStudents: 1876,
    rating: 4.7,
    totalRatings: 215,
    price: 2499,
    originalPrice: 4999,
    isFree: false,
    isPopular: false,
    features: [
      '42 Visual Mechanism Lessons',
      'Reaction Roadmaps & Named Reactions Guide',
      'Physical Chemistry Numerical Cheat Sheets',
      'Weekly Doubt Clearing Classes'
    ],
    syllabus: [
      'Basic Concepts of Chemistry & Mole Concept',
      'Structure of Atom & Quantum Numbers',
      'Periodic Classification & Chemical Bonding',
      'GOC - General Organic Chemistry & Intermediates'
    ],
    lessons: [
      { id: 'l_301', title: '01. Mole Concept & Stoichiometry Equations', duration: '24:30', isCompleted: true, isFree: true, order: 1 },
      { id: 'l_302', title: '02. Bohr\'s Model & De Broglie Hypothesis', duration: '29:00', isCompleted: true, isFree: true, order: 2 },
      { id: 'l_303', title: '03. Hybridization & VSEPR Molecular Geometry', duration: '34:20', isCompleted: true, isFree: false, order: 3 },
      { id: 'l_304', title: '04. Electrophiles, Nucleophiles & Resonance', duration: '40:15', isCompleted: false, isFree: false, order: 4 },
    ],
  },
  {
    id: 'c_004',
    title: 'Biology Complete NEET Prep',
    description: 'High-yield NCERT line-by-line coverage for Botany and Zoology. Covers cell biology, genetics, human physiology, biotechnology, and ecology.',
    shortDescription: 'Complete NCERT line-by-line preparation for 360/360 in NEET Biology.',
    thumbnail: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&h=500&fit=crop',
    instructor: {
      id: 'inst_004',
      name: 'Dr. Ravi Verma',
      qualification: 'MBBS, Top Faculty AIIMS Rankers',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop',
    },
    category: 'Science',
    level: 'Intermediate',
    duration: '45 hours',
    totalLessons: 54,
    totalStudents: 1456,
    rating: 4.8,
    totalRatings: 180,
    price: 2799,
    originalPrice: 5499,
    isFree: false,
    isPopular: true,
    features: [
      'NCERT Line-by-Line Audio-Visual Breakdown',
      'Color Diagrams & Mindmaps',
      '10,000+ Topic Wise Flashcards',
      'Previous 15 Years NEET Question Analysis'
    ],
    syllabus: [
      'Diversity in Living World & Plant Kingdom',
      'Structural Organisation in Animals & Plants',
      'Cell Biology: Unit of Life & Cell Cycle',
      'Human Physiology & Organ Systems'
    ],
    lessons: [
      { id: 'l_401', title: '01. The Living World & Taxonomic Keys', duration: '19:45', isCompleted: false, isFree: true, order: 1 },
      { id: 'l_402', title: '02. Biological Classification - Five Kingdom System', duration: '31:10', isCompleted: false, isFree: true, order: 2 },
      { id: 'l_403', title: '03. Cell Organelles: Mitochondria, ER & Golgi', duration: '28:50', isCompleted: false, isFree: false, order: 3 },
    ],
  },
  {
    id: 'c_005',
    title: 'English Grammar & Writing Skills',
    description: 'Enhance your communication, formal letter writing, reading comprehension, and grammar rules for board exams and competitive aptitude tests.',
    shortDescription: 'Master grammar, vocabulary and advanced composition skills.',
    thumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=500&fit=crop',
    instructor: {
      id: 'inst_005',
      name: 'Ms. Sarah Wilson',
      qualification: 'M.A. English Literature',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop',
    },
    category: 'Language',
    level: 'Beginner',
    duration: '25 hours',
    totalLessons: 30,
    totalStudents: 3245,
    rating: 4.9,
    totalRatings: 420,
    price: 0,
    originalPrice: 1999,
    isFree: true,
    isPopular: false,
    features: [
      'Comprehensive Grammar Drills',
      'Letter, Notice & Essay Writing Templates',
      'Vocabulary Building Flashcards'
    ],
    syllabus: [
      'Tenses & Subject-Verb Agreement',
      'Active & Passive Voice Transformation',
      'Reported Speech & Direct-Indirect Conversion',
      'Formal Letter & Email Formats'
    ],
    lessons: [
      { id: 'l_501', title: '01. Parts of Speech & Sentence Syntax', duration: '18:15', isCompleted: true, isFree: true, order: 1 },
      { id: 'l_502', title: '02. Tenses Masterclass with Live Examples', duration: '26:00', isCompleted: false, isFree: true, order: 2 },
    ],
  },
  {
    id: 'c_006',
    title: 'Computer Science & Python Coding',
    description: 'Learn computational logic, algorithmic thinking, Python 3 syntax, data structures, and basic SQL for CBSE Class 11 & 12 Computer Science.',
    shortDescription: 'Learn Python programming, algorithms, and database queries.',
    thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&h=500&fit=crop',
    instructor: {
      id: 'inst_006',
      name: 'Er. Vikram Patel',
      qualification: 'B.Tech CSE, Ex-Software Architect',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop',
    },
    category: 'Technology',
    level: 'Beginner',
    duration: '50 hours',
    totalLessons: 60,
    totalStudents: 4521,
    rating: 4.9,
    totalRatings: 610,
    price: 1999,
    originalPrice: 3999,
    isFree: false,
    isPopular: true,
    features: [
      '60 Practical Hands-on Coding Videos',
      '100+ Python Algorithm Exercises',
      'SQL Queries & MySQL Integration',
      'Full CBSE Board Capstone Project Code'
    ],
    syllabus: [
      'Python Basics: Variables, Loops & Conditionals',
      'Functions, Modules & File Handling',
      'Data Structures: Lists, Tuples & Dictionaries',
      'Relational Databases & SQL Queries'
    ],
    lessons: [
      { id: 'l_601', title: '01. Setting Up Python & First Script', duration: '15:20', isCompleted: false, isFree: true, order: 1 },
      { id: 'l_602', title: '02. Control Flow: If-Else & While Loops', duration: '28:10', isCompleted: false, isFree: true, order: 2 },
    ],
  },
];

export const dummyTests: Test[] = [
  {
    id: 't_001',
    title: 'Physics: Laws of Motion & Friction',
    description: 'Comprehensive 15-question diagnostic test on Newton\'s Laws, Free Body Diagrams, Pulley Systems, and Friction. Designed on latest JEE Main pattern.',
    subject: 'Physics',
    standard: 'Class 11 / 12 / Dropper',
    durationMinutes: 20,
    totalMarks: 60,
    passingMarks: 24,
    questionsCount: 5,
    difficulty: 'Medium',
    questions: [
      {
        id: 'q_1',
        questionText: 'A block of mass 5 kg is placed on a rough horizontal surface with coefficient of friction μ = 0.4. If a horizontal force of 15 N is applied to the block, what is the magnitude of the frictional force acting on it? (Take g = 10 m/s²)',
        options: ['15 N', '20 N', '0 N', '50 N'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'Maximum static friction f_max = μ * N = 0.4 * (5 * 10) = 20 N. Since the applied force (15 N) is less than f_max, the block remains stationary and static friction equals the applied force: 15 N.',
      },
      {
        id: 'q_2',
        questionText: 'Which of the following frames of reference is strictly an inertial frame of reference?',
        options: [
          'A car moving with uniform velocity on a straight road',
          'A rotating merry-go-round',
          'An elevator accelerating upwards',
          'A satellite in orbit around the Earth'
        ],
        correctAnswer: 0,
        marks: 4,
        explanation: 'An inertial frame of reference is one in which Newton\'s first law holds true, meaning the frame is non-accelerating (moving with constant velocity or at rest).',
      },
      {
        id: 'q_3',
        questionText: 'Two bodies of masses 2 kg and 4 kg are connected by a light string passing over a frictionless pulley. What is the acceleration of the system? (Take g = 10 m/s²)',
        options: ['3.33 m/s²', '5.0 m/s²', '2.5 m/s²', '1.67 m/s²'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'a = (m2 - m1)g / (m1 + m2) = (4 - 2)*10 / (4 + 2) = 20 / 6 = 3.33 m/s².',
      },
      {
        id: 'q_4',
        questionText: 'A bullet of mass 10 g leaves a rifle with a velocity of 400 m/s. If the mass of the rifle is 4 kg, what is the recoil velocity of the rifle?',
        options: ['-1.0 m/s', '-2.0 m/s', '-4.0 m/s', '-0.5 m/s'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'By conservation of linear momentum: m_bullet * v_bullet + m_rifle * v_rifle = 0 => (0.01 kg * 400) + 4 * v = 0 => 4 + 4v = 0 => v = -1 m/s.',
      },
      {
        id: 'q_5',
        questionText: 'A passenger standing in a bus falls backward when the bus suddenly accelerates forward. This phenomenon is an example of:',
        options: ['Inertia of rest', 'Inertia of motion', 'Inertia of direction', 'Action-reaction pair'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'The passenger\'s lower body moves forward with the bus while the upper body tends to remain at rest due to inertia of rest.',
      },
    ],
  },
  {
    id: 't_002',
    title: 'Mathematics: Differential Calculus & Limits',
    description: 'Test your understanding of standard limits, continuity check, first principles, and product/quotient rules of differentiation.',
    subject: 'Mathematics',
    standard: 'Class 12 / JEE',
    durationMinutes: 15,
    totalMarks: 40,
    passingMarks: 16,
    questionsCount: 4,
    difficulty: 'Hard',
    questions: [
      {
        id: 'qm_1',
        questionText: 'Evaluate the limit: lim (x -> 0) [sin(3x) / tan(2x)]',
        options: ['3/2', '2/3', '1', '0'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'lim (x -> 0) [ (sin(3x)/(3x)) * 3 / ((tan(2x)/(2x)) * 2) ] = 1 * 3 / (1 * 2) = 3/2.',
      },
      {
        id: 'qm_2',
        questionText: 'If y = ln(sec(x) + tan(x)), what is dy/dx?',
        options: ['sec(x)', 'tan(x)', 'sec(x) * tan(x)', 'cos(x)'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'dy/dx = (1 / (sec x + tan x)) * (sec x tan x + sec² x) = sec x (tan x + sec x) / (sec x + tan x) = sec x.',
      },
      {
        id: 'qm_3',
        questionText: 'The derivative of e^(x²) with respect to x is:',
        options: ['2x * e^(x²)', 'e^(x²)', 'x² * e^(x² - 1)', '2 * e^(x)'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'Using the chain rule: d/dx[e^(u)] = e^(u) * du/dx, where u = x² and du/dx = 2x. Thus 2x * e^(x²).',
      },
      {
        id: 'qm_4',
        questionText: 'What is the slope of the tangent to the curve y = x³ - 3x + 2 at x = 2?',
        options: ['9', '6', '12', '3'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'dy/dx = 3x² - 3. At x = 2, slope = 3(2)² - 3 = 12 - 3 = 9.',
      },
    ],
  },
  {
    id: 't_003',
    title: 'Chemistry: Mole Concept & Chemical Bonding',
    description: 'High-frequency conceptual test covering stoichiometry, molar volume, Lewis structures, and hybridization.',
    subject: 'Chemistry',
    standard: 'Class 11 / NEET',
    durationMinutes: 15,
    totalMarks: 40,
    passingMarks: 16,
    questionsCount: 4,
    difficulty: 'Easy',
    questions: [
      {
        id: 'qc_1',
        questionText: 'What is the number of moles of water molecules present in 180 g of pure water? (Molar mass of H2O = 18 g/mol)',
        options: ['10 moles', '1 mole', '18 moles', '100 moles'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'Moles = mass / molar mass = 180 / 18 = 10 moles.',
      },
      {
        id: 'qc_2',
        questionText: 'What is the hybridization of the central Carbon atom in methane (CH4)?',
        options: ['sp³', 'sp²', 'sp', 'dsp²'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'Carbon has 4 single sigma bonds and 0 lone pairs, giving a steric number of 4, which corresponds to sp³ hybridization.',
      },
      {
        id: 'qc_3',
        questionText: 'What is the volume occupied by 1 mole of an ideal gas at Standard Temperature and Pressure (STP)?',
        options: ['22.4 Litres', '11.2 Litres', '44.8 Litres', '24.0 Litres'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'At standard STP (0°C and 1 atm), 1 mole of any ideal gas occupies 22.4 litres.',
      },
      {
        id: 'qc_4',
        questionText: 'Which molecule has a dipole moment equal to zero due to symmetrical shape?',
        options: ['CO2 (Carbon Dioxide)', 'H2O (Water)', 'NH3 (Ammonia)', 'SO2 (Sulfur Dioxide)'],
        correctAnswer: 0,
        marks: 4,
        explanation: 'CO2 is linear (O=C=O) with bond dipoles pointing in opposite directions, cancelling out to give a net dipole moment of 0.',
      },
    ],
  },
];

export const dummyLiveSessions: LiveSession[] = [
  {
    id: 'live_001',
    title: 'Ray Optics: Lens Maker Formula & Aberrations',
    subject: 'Physics',
    standard: 'Class 12 - Target JEE 2025',
    instructor: 'Dr. Priya Singh',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop',
    scheduledTime: '06:00 PM',
    scheduledDate: 'Today',
    durationMinutes: 75,
    status: 'live',
    participantsCount: 142,
  },
  {
    id: 'live_002',
    title: 'Definite Integration Properties & Shortcuts',
    subject: 'Mathematics',
    standard: 'Class 12 - Target JEE 2025',
    instructor: 'Prof. Amit Kumar',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop',
    scheduledTime: '07:30 PM',
    scheduledDate: 'Today',
    durationMinutes: 90,
    status: 'upcoming',
    participantsCount: 88,
  },
  {
    id: 'live_003',
    title: 'Coordination Compounds: Crystal Field Theory',
    subject: 'Chemistry',
    standard: 'Class 12 - NEET Track',
    instructor: 'Dr. Neha Gupta',
    instructorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    scheduledTime: '10:00 AM',
    scheduledDate: 'Tomorrow',
    durationMinutes: 60,
    status: 'upcoming',
  },
];

export const dummyVideoLectures: VideoLecture[] = [
  {
    id: 'vid_001',
    title: 'Rotational Motion: Rolling without Slipping',
    description: 'Understand pure rolling on inclined planes and friction requirements with solved IIT questions.',
    subject: 'Physics',
    standard: 'Class 11',
    duration: '42:18',
    instructor: 'Dr. Priya Singh',
    thumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&h=350&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    views: 3420,
  },
  {
    id: 'vid_002',
    title: 'Probability & Bayes Theorem Made Easy',
    description: 'Visual explanation of conditional probability, total probability theorem, and reverse conditioning.',
    subject: 'Mathematics',
    standard: 'Class 12',
    duration: '38:50',
    instructor: 'Prof. Amit Kumar',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=350&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    views: 4890,
  },
  {
    id: 'vid_003',
    title: 'Aldehydes & Ketones: Nucleophilic Addition',
    description: 'Detailed reaction mechanisms for Grignard reagents, Aldol condensation, and Cannizzaro reaction.',
    subject: 'Chemistry',
    standard: 'Class 12',
    duration: '46:12',
    instructor: 'Dr. Neha Gupta',
    thumbnail: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=600&h=350&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    views: 2980,
  },
  {
    id: 'vid_004',
    title: 'Human Circulatory System & Cardiac Cycle',
    description: 'ECG interpretation, double circulation, and cardiac output calculation for NEET aspirants.',
    subject: 'Biology',
    standard: 'Class 11',
    duration: '35:40',
    instructor: 'Dr. Ravi Verma',
    thumbnail: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&h=350&fit=crop',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    views: 5210,
  },
];

export const dummyNotices: Notice[] = [
  {
    id: 'not_001',
    title: 'Patna Center: All India Mock Test 03 Schedule',
    message: 'The third offline All India JEE/NEET Mock Test will be conducted this Sunday from 09:00 AM to 12:00 PM at Kankarbagh Main Center. Students must bring their Raven ID cards.',
    postedBy: 'Academic Director',
    category: 'Exam',
    date: '10 Sep 2026',
    isImportant: true,
  },
  {
    id: 'not_002',
    title: 'Special Sunday Doubt Clearing Camp with IIT Faculty',
    message: 'One-on-one 15-minute doubt sessions will be held for Physics and Chemistry this Sunday. Pre-book your slot in the Raven Hub to avoid queues.',
    postedBy: 'Administration',
    category: 'Academic',
    date: '08 Sep 2026',
    isImportant: false,
  },
  {
    id: 'not_003',
    title: 'Class 10 & 12 Board Examination Crash Course Launched',
    message: 'A 60-day intensive board revision series with chapter summaries, previous 10-year question solving, and answer writing evaluation is now available on the portal.',
    postedBy: 'Examination Cell',
    category: 'General',
    date: '05 Sep 2026',
    isImportant: false,
  },
];

export const dummyTestimonials: Testimonial[] = [
  {
    id: 'testi_1',
    name: 'Ananya Mishra',
    role: 'JEE Advanced AIR 412',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    content: 'Raven Tutorials helped me crack JEE Advanced with flying colors! The teachers are always available and the test series mirrored the exact exam interface.',
    rating: 5,
  },
  {
    id: 'testi_2',
    name: 'Rohit Agarwal',
    role: 'NEET AIR 680 Score',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    content: 'The biology and chemistry courses are exceptionally detailed. I scored 680+ thanks to Dr. Neha Gupta and Dr. Ravi Verma\'s test discussions.',
    rating: 5,
  },
  {
    id: 'testi_3',
    name: 'Priya Patel',
    role: 'Class 12 CBSE Topper (98.4%)',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    content: 'The doubt support system is instantaneous. The teachers never hesitate to re-explain a concept until you have 100% confidence.',
    rating: 5,
  },
];

export const platformStats = {
  totalStudents: '15,400+',
  totalCourses: '150+',
  expertFaculty: '45+',
  successRate: '98.2%',
  testsTaken: '85,000+',
};

export const studentEnrollments = [
  {
    courseId: 'c_001',
    courseName: 'Complete Physics Masterclass',
    courseTitle: 'Complete Physics Masterclass',
    status: 'Active',
    progress: 68,
    batchTime: 'Daily 4:00 PM - 6:00 PM',
    lastAccessed: 'Today, 2:30 PM',
  },
  {
    courseId: 'c_002',
    courseName: 'Advanced Mathematics for JEE',
    courseTitle: 'Advanced Mathematics for JEE',
    status: 'Active',
    progress: 42,
    batchTime: 'Daily 6:15 PM - 8:15 PM',
    lastAccessed: 'Yesterday',
  },
  {
    courseId: 'c_003',
    courseName: 'Chemistry Fundamentals & Reactions',
    courseTitle: 'Chemistry Fundamentals & Reactions',
    status: 'Active',
    progress: 85,
    batchTime: 'Daily 2:00 PM - 3:45 PM',
    lastAccessed: '3 days ago',
  },
];
